"""GitHub client, PR parser, and polling service (Phase 2)."""

from __future__ import annotations

from github_.client import (
    DEFAULT_BASE_URL,
    GitHubAPIError,
    GitHubAuthError,
    GitHubClient,
)
from github_.diff import DiffLine, Hunk, LineKind, parse_patch
from github_.models import (
    Branch,
    BranchCommit,
    CommitAuthor,
    CommitInfo,
    Issue,
    IssueComment,
    Label,
    PullRequest,
    PullRequestCommit,
    PullRequestFile,
    PullRequestRef,
    PullRequestReview,
    PullRequestReviewComment,
    PullRequestState,
    PullRequestSummary,
    Repository,
    Review,
    ReviewComment,
    ReviewEvent,
    User,
)
from github_.polling import EventKind, Handler, PollEvent, PollingService
from github_.pr import (
    LinkedIssue,
    LinkedIssueReference,
    ParsedFile,
    PullRequestParser,
    PullRequestPayload,
)
from github_.pr_commands import (
    CommandKind,
    CommandState,
    CommandStateStore,
    FileCommandStateStore,
    InMemoryCommandStateStore,
    PullRequestCommand,
    parse_openrabbit_command,
)
from github_.repository import RepositoryHandle
from github_.state import (
    FileStateStore,
    InMemoryStateStore,
    PollState,
    SeenPullRequest,
    StateStore,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "Branch",
    "BranchCommit",
    "CommandKind",
    "CommandState",
    "CommandStateStore",
    "CommitAuthor",
    "CommitInfo",
    "DiffLine",
    "EventKind",
    "FileCommandStateStore",
    "FileStateStore",
    "GitHubAPIError",
    "GitHubAuthError",
    "GitHubClient",
    "Handler",
    "Hunk",
    "InMemoryCommandStateStore",
    "InMemoryStateStore",
    "Issue",
    "IssueComment",
    "Label",
    "LineKind",
    "LinkedIssue",
    "LinkedIssueReference",
    "ParsedFile",
    "PollEvent",
    "PollState",
    "PollingService",
    "PullRequest",
    "PullRequestCommand",
    "PullRequestCommit",
    "PullRequestFile",
    "PullRequestParser",
    "PullRequestPayload",
    "PullRequestRef",
    "PullRequestReview",
    "PullRequestReviewComment",
    "PullRequestState",
    "PullRequestSummary",
    "Repository",
    "RepositoryHandle",
    "Review",
    "ReviewComment",
    "ReviewEvent",
    "SeenPullRequest",
    "StateStore",
    "User",
    "parse_openrabbit_command",
    "parse_patch",
]
